version: "3.7"
services:
  frontend:
    image: paperless:nginx
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"
  backend:
    image: paperless:openjdk
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    #depends_on:
     # postgres:
      #  condition: service_started

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: swkom
    ports:
      - "5432:5432"

